import React, { useState, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { 
  Plus, 
  Filter, 
  Search,
  Calendar,
  User,
  Clock,
  CheckCircle,
  AlertCircle,
  Play,
  MoreHorizontal,
  Edit,
  Trash2,
  Eye,
  Bot,
  Zap,
  Target,
  BarChart3,
  Activity,
  Flag,
  Timer,
  Users,
  FileText,
  Link,
  MessageSquare,
  ChevronDown,
  ChevronRight,
  DragHandleDots2
} from "lucide-react";

// Types for the project board data
interface Task {
  id: string;
  title: string;
  description?: string;
  status: 'backlog' | 'todo' | 'in_progress' | 'review' | 'testing' | 'done' | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  assignee?: string;
  assigneeId?: string;
  dueDate?: string;
  storyPoints?: number;
  estimatedHours?: number;
  actualHours?: number;
  acceptanceCriteria?: string[];
  aiGenerated?: boolean;
  aiConfidence?: number;
  aiNotes?: string;
  attachments?: Array<{name: string; url: string; type: string; size: number}>;
  externalLinks?: Array<{title: string; url: string; type: string}>;
  createdAt: string;
  updatedAt: string;
}

interface Sprint {
  id: string;
  name: string;
  description?: string;
  status: 'planning' | 'active' | 'completed' | 'cancelled';
  startDate?: string;
  endDate?: string;
  plannedVelocity: number;
  actualVelocity: number;
  goals: string[];
  successCriteria: string[];
  tasks: Task[];
}

interface Blocker {
  id: string;
  title: string;
  description?: string;
  type: 'impediment' | 'dependency' | 'resource' | 'technical' | 'external';
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'in_progress' | 'resolved' | 'cancelled';
  taskId?: string;
  slaDeadline?: string;
  escalationLevel: number;
  createdAt: string;
  updatedAt: string;
}

interface ActivityLog {
  id: string;
  action: string;
  description: string;
  entityType: 'project' | 'sprint' | 'task' | 'blocker' | 'assignment';
  entityId: string;
  actorType: 'user' | 'agent' | 'system';
  actorName?: string;
  agentName?: string;
  createdAt: string;
}

// Mock data
const mockSprints: Sprint[] = [
  {
    id: '1',
    name: 'Sprint 1 - Foundation',
    description: 'Set up project foundation and core features',
    status: 'active',
    startDate: '2024-12-20',
    endDate: '2024-12-27',
    plannedVelocity: 20,
    actualVelocity: 15,
    goals: ['Complete user authentication', 'Set up database schema', 'Implement core API'],
    successCriteria: ['All tests passing', 'Code review completed', 'Deployed to staging'],
    tasks: [
      {
        id: '1',
        title: 'Design user authentication flow',
        description: 'Create comprehensive auth system with JWT tokens',
        status: 'in_progress',
        priority: 'high',
        assignee: 'Sarah Johnson',
        assigneeId: 'user1',
        dueDate: '2024-12-22',
        storyPoints: 5,
        estimatedHours: 8,
        actualHours: 4,
        acceptanceCriteria: [
          'User can register with email/password',
          'User can login and receive JWT token',
          'Password reset functionality works',
          'Email verification is implemented'
        ],
        aiGenerated: true,
        aiConfidence: 0.85,
        aiNotes: 'Generated by PM Agent based on project requirements',
        attachments: [
          { name: 'auth-flow-diagram.pdf', url: '/files/auth-flow.pdf', type: 'pdf', size: 1024000 }
        ],
        externalLinks: [
          { title: 'JWT Best Practices', url: 'https://example.com/jwt', type: 'documentation' }
        ],
        createdAt: '2024-12-20T10:00:00Z',
        updatedAt: '2024-12-20T14:30:00Z'
      },
      {
        id: '2',
        title: 'Implement payment gateway integration',
        description: 'Integrate Stripe payment processing',
        status: 'todo',
        priority: 'high',
        assignee: 'Mike Chen',
        assigneeId: 'user2',
        dueDate: '2024-12-24',
        storyPoints: 8,
        estimatedHours: 12,
        acceptanceCriteria: [
          'Stripe webhook handling implemented',
          'Payment processing works for all card types',
          'Error handling for failed payments',
          'Test mode integration completed'
        ],
        aiGenerated: true,
        aiConfidence: 0.92,
        aiNotes: 'Generated by PM Agent with high confidence based on similar projects',
        createdAt: '2024-12-20T10:00:00Z',
        updatedAt: '2024-12-20T10:00:00Z'
      },
      {
        id: '3',
        title: 'Create product catalog component',
        description: 'Build reusable product listing and detail components',
        status: 'done',
        priority: 'medium',
        assignee: 'John Smith',
        assigneeId: 'user3',
        dueDate: '2024-12-21',
        storyPoints: 3,
        estimatedHours: 6,
        actualHours: 5.5,
        acceptanceCriteria: [
          'Product grid displays correctly',
          'Search and filter functionality works',
          'Responsive design implemented',
          'Loading states handled'
        ],
        aiGenerated: false,
        createdAt: '2024-12-20T10:00:00Z',
        updatedAt: '2024-12-21T16:00:00Z'
      }
    ]
  }
];

const mockBlockers: Blocker[] = [
  {
    id: '1',
    title: 'Stripe API key configuration issue',
    description: 'Unable to connect to Stripe test environment due to API key configuration',
    type: 'technical',
    severity: 'high',
    status: 'open',
    taskId: '2',
    slaDeadline: '2024-12-21T18:00:00Z',
    escalationLevel: 1,
    createdAt: '2024-12-20T15:00:00Z',
    updatedAt: '2024-12-20T15:00:00Z'
  },
  {
    id: '2',
    title: 'Design system approval pending',
    description: 'Waiting for client approval on new design system components',
    type: 'external',
    severity: 'medium',
    status: 'open',
    slaDeadline: '2024-12-23T12:00:00Z',
    escalationLevel: 0,
    createdAt: '2024-12-20T11:00:00Z',
    updatedAt: '2024-12-20T11:00:00Z'
  }
];

const mockActivityLogs: ActivityLog[] = [
  {
    id: '1',
    action: 'task_created',
    description: 'Task "Design user authentication flow" created by PM Agent',
    entityType: 'task',
    entityId: '1',
    actorType: 'agent',
    agentName: 'PM Agent',
    createdAt: '2024-12-20T10:00:00Z'
  },
  {
    id: '2',
    action: 'task_assigned',
    description: 'Task assigned to Sarah Johnson',
    entityType: 'task',
    entityId: '1',
    actorType: 'agent',
    agentName: 'PM Agent',
    createdAt: '2024-12-20T10:05:00Z'
  },
  {
    id: '3',
    action: 'status_changed',
    description: 'Task status changed from todo to in_progress',
    entityType: 'task',
    entityId: '1',
    actorType: 'user',
    actorName: 'Sarah Johnson',
    createdAt: '2024-12-20T14:30:00Z'
  },
  {
    id: '4',
    action: 'blocker_created',
    description: 'Blocker "Stripe API key configuration issue" created',
    entityType: 'blocker',
    entityId: '1',
    actorType: 'user',
    actorName: 'Mike Chen',
    createdAt: '2024-12-20T15:00:00Z'
  }
];

export default function ProjectBoard() {
  const [selectedSprint, setSelectedSprint] = useState<Sprint | null>(mockSprints[0]);
  const [viewMode, setViewMode] = useState<'kanban' | 'backlog' | 'timeline'>('kanban');
  const [showAIPlanner, setShowAIPlanner] = useState(false);
  const [showBlockerTracker, setShowBlockerTracker] = useState(false);
  const [showActivityTimeline, setShowActivityTimeline] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterPriority, setFilterPriority] = useState<string>('all');

  // Filter tasks based on search and filters
  const filteredTasks = selectedSprint?.tasks.filter(task => {
    const matchesSearch = task.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         task.description?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = filterStatus === 'all' || task.status === filterStatus;
    const matchesPriority = filterPriority === 'all' || task.priority === filterPriority;
    return matchesSearch && matchesStatus && matchesPriority;
  }) || [];

  // Group tasks by status for Kanban view
  const tasksByStatus = {
    backlog: filteredTasks.filter(task => task.status === 'backlog'),
    todo: filteredTasks.filter(task => task.status === 'todo'),
    in_progress: filteredTasks.filter(task => task.status === 'in_progress'),
    review: filteredTasks.filter(task => task.status === 'review'),
    testing: filteredTasks.filter(task => task.status === 'testing'),
    done: filteredTasks.filter(task => task.status === 'done')
  };

  const statusConfig = {
    backlog: { label: 'Backlog', color: 'bg-gray-500', icon: '📋' },
    todo: { label: 'To Do', color: 'bg-blue-500', icon: '📝' },
    in_progress: { label: 'In Progress', color: 'bg-yellow-500', icon: '⚡' },
    review: { label: 'Review', color: 'bg-purple-500', icon: '👀' },
    testing: { label: 'Testing', color: 'bg-orange-500', icon: '🧪' },
    done: { label: 'Done', color: 'bg-green-500', icon: '✅' }
  };

  const priorityConfig = {
    low: { label: 'Low', color: 'bg-gray-100 text-gray-800', icon: '🔽' },
    medium: { label: 'Medium', color: 'bg-blue-100 text-blue-800', icon: '🔼' },
    high: { label: 'High', color: 'bg-orange-100 text-orange-800', icon: '🔺' },
    urgent: { label: 'Urgent', color: 'bg-red-100 text-red-800', icon: '🚨' }
  };

  const getSLAStatus = (deadline: string) => {
    const now = new Date();
    const deadlineDate = new Date(deadline);
    const hoursUntilDeadline = (deadlineDate.getTime() - now.getTime()) / (1000 * 60 * 60);
    
    if (hoursUntilDeadline < 0) return { status: 'breached', color: 'text-red-500' };
    if (hoursUntilDeadline < 24) return { status: 'at_risk', color: 'text-orange-500' };
    return { status: 'on_track', color: 'text-green-500' };
  };

  const TaskCard = ({ task }: { task: Task }) => (
    <Card className="mb-3 p-4 hover:shadow-md transition-shadow cursor-pointer group">
      <div className="space-y-3">
        <div className="flex items-start justify-between">
          <h4 className="font-medium text-sm leading-tight">{task.title}</h4>
          <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
            <Button variant="ghost" size="sm" className="h-6 w-6 p-0">
              <Edit className="h-3 w-3" />
            </Button>
            <Button variant="ghost" size="sm" className="h-6 w-6 p-0">
              <MoreHorizontal className="h-3 w-3" />
            </Button>
          </div>
        </div>
        
        {task.description && (
          <p className="text-xs text-muted-foreground line-clamp-2">{task.description}</p>
        )}

        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Badge 
              size="sm" 
              className={`${priorityConfig[task.priority].color} text-xs`}
            >
              {priorityConfig[task.priority].icon} {priorityConfig[task.priority].label}
            </Badge>
            {task.aiGenerated && (
              <Badge size="sm" variant="outline" className="text-xs">
                <Bot className="h-3 w-3 mr-1" />
                AI
              </Badge>
            )}
          </div>
          
          {task.storyPoints && (
            <div className="flex items-center gap-1 text-xs text-muted-foreground">
              <Target className="h-3 w-3" />
              {task.storyPoints} pts
            </div>
          )}
        </div>

        {task.assignee && (
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 bg-primary rounded-full flex items-center justify-center text-xs text-primary-foreground">
              {task.assignee.split(' ').map(n => n[0]).join('')}
            </div>
            <span className="text-xs text-muted-foreground">{task.assignee}</span>
          </div>
        )}

        {task.dueDate && (
          <div className="flex items-center gap-1 text-xs text-muted-foreground">
            <Calendar className="h-3 w-3" />
            {new Date(task.dueDate).toLocaleDateString()}
          </div>
        )}

        {task.aiConfidence && (
          <div className="flex items-center gap-1 text-xs">
            <div className="flex items-center gap-1">
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
              <span className="text-muted-foreground">AI Confidence: {Math.round(task.aiConfidence * 100)}%</span>
            </div>
          </div>
        )}

        {task.attachments && task.attachments.length > 0 && (
          <div className="flex items-center gap-1 text-xs text-muted-foreground">
            <FileText className="h-3 w-3" />
            {task.attachments.length} attachment{task.attachments.length > 1 ? 's' : ''}
          </div>
        )}

        {task.externalLinks && task.externalLinks.length > 0 && (
          <div className="flex items-center gap-1 text-xs text-muted-foreground">
            <Link className="h-3 w-3" />
            {task.externalLinks.length} link{task.externalLinks.length > 1 ? 's' : ''}
          </div>
        )}
      </div>
    </Card>
  );

  const BlockerCard = ({ blocker }: { blocker: Blocker }) => {
    const slaStatus = blocker.slaDeadline ? getSLAStatus(blocker.slaDeadline) : null;
    
    return (
      <Card className="mb-3 p-4 border-l-4 border-l-red-500">
        <div className="space-y-2">
          <div className="flex items-start justify-between">
            <h4 className="font-medium text-sm">{blocker.title}</h4>
            <Badge 
              size="sm" 
              variant={blocker.severity === 'critical' ? 'destructive' : 'secondary'}
            >
              {blocker.severity.toUpperCase()}
            </Badge>
          </div>
          
          {blocker.description && (
            <p className="text-xs text-muted-foreground">{blocker.description}</p>
          )}
          
          <div className="flex items-center justify-between text-xs">
            <span className="text-muted-foreground">{blocker.type}</span>
            {slaStatus && (
              <span className={slaStatus.color}>
                <Timer className="h-3 w-3 inline mr-1" />
                {slaStatus.status}
              </span>
            )}
          </div>
          
          {blocker.escalationLevel > 0 && (
            <div className="flex items-center gap-1 text-xs text-orange-600">
              <Flag className="h-3 w-3" />
              Escalated (Level {blocker.escalationLevel})
            </div>
          )}
        </div>
      </Card>
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Project Board</h1>
          <p className="text-muted-foreground">
            AI-powered project management and sprint planning
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setShowAIPlanner(true)}>
            <Bot className="w-4 h-4 mr-2" />
            AI Sprint Planner
          </Button>
          <Button variant="outline" onClick={() => setShowBlockerTracker(true)}>
            <Flag className="w-4 h-4 mr-2" />
            Blockers ({mockBlockers.length})
          </Button>
          <Button variant="outline" onClick={() => setShowActivityTimeline(true)}>
            <Activity className="w-4 h-4 mr-2" />
            Activity
          </Button>
          <Button className="bg-primary text-primary-foreground hover:bg-primary/90">
            <Plus className="w-4 h-4 mr-2" />
            New Task
          </Button>
        </div>
      </div>

      {/* Sprint Selector */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-lg">Current Sprint</CardTitle>
              <CardDescription>
                {selectedSprint?.name} • {selectedSprint?.status.toUpperCase()}
              </CardDescription>
            </div>
            <Select value={selectedSprint?.id} onValueChange={(value) => {
              const sprint = mockSprints.find(s => s.id === value);
              setSelectedSprint(sprint || null);
            }}>
              <SelectTrigger className="w-48">
                <SelectValue placeholder="Select sprint" />
              </SelectTrigger>
              <SelectContent>
                {mockSprints.map((sprint) => (
                  <SelectItem key={sprint.id} value={sprint.id}>
                    {sprint.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">{selectedSprint?.plannedVelocity}</div>
              <div className="text-sm text-muted-foreground">Planned Velocity</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-green-600">{selectedSprint?.actualVelocity}</div>
              <div className="text-sm text-muted-foreground">Actual Velocity</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-blue-600">{selectedSprint?.tasks.length}</div>
              <div className="text-sm text-muted-foreground">Total Tasks</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-orange-600">{mockBlockers.length}</div>
              <div className="text-sm text-muted-foreground">Active Blockers</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Filters and Search */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-1">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search tasks..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
            <div className="flex gap-2">
              <Select value={filterStatus} onValueChange={setFilterStatus}>
                <SelectTrigger className="w-32">
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="backlog">Backlog</SelectItem>
                  <SelectItem value="todo">To Do</SelectItem>
                  <SelectItem value="in_progress">In Progress</SelectItem>
                  <SelectItem value="review">Review</SelectItem>
                  <SelectItem value="testing">Testing</SelectItem>
                  <SelectItem value="done">Done</SelectItem>
                </SelectContent>
              </Select>
              <Select value={filterPriority} onValueChange={setFilterPriority}>
                <SelectTrigger className="w-32">
                  <SelectValue placeholder="Priority" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Priority</SelectItem>
                  <SelectItem value="low">Low</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="urgent">Urgent</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Main Content Tabs */}
      <Tabs value={viewMode} onValueChange={(value) => setViewMode(value as any)}>
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="kanban">Kanban Board</TabsTrigger>
          <TabsTrigger value="backlog">Backlog</TabsTrigger>
          <TabsTrigger value="timeline">Timeline</TabsTrigger>
        </TabsList>

        <TabsContent value="kanban" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Task Board</CardTitle>
              <CardDescription>
                Drag and drop tasks between columns to update status
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
                {Object.entries(statusConfig).map(([status, config]) => (
                  <div key={status} className="space-y-3">
                    <div className="flex items-center gap-2 mb-4">
                      <div className={`w-3 h-3 ${config.color} rounded-full`}></div>
                      <h3 className="font-semibold text-sm">{config.label}</h3>
                      <Badge variant="secondary" className="text-xs">
                        {tasksByStatus[status as keyof typeof tasksByStatus].length}
                      </Badge>
                    </div>
                    <div className="space-y-2 min-h-[200px]">
                      {tasksByStatus[status as keyof typeof tasksByStatus].map((task) => (
                        <TaskCard key={task.id} task={task} />
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="backlog" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Task Backlog</CardTitle>
              <CardDescription>
                All tasks organized by priority and status
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {filteredTasks.map((task) => (
                  <TaskCard key={task.id} task={task} />
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="timeline" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Project Timeline</CardTitle>
              <CardDescription>
                Task progress and milestones over time
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-64 flex items-center justify-center text-muted-foreground">
                <div className="text-center">
                  <BarChart3 className="h-12 w-12 mx-auto mb-4" />
                  <p>Timeline view coming soon</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* AI Sprint Planner Dialog */}
      <Dialog open={showAIPlanner} onOpenChange={setShowAIPlanner}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Bot className="h-5 w-5" />
              AI Sprint Planner
            </DialogTitle>
            <DialogDescription>
              Generate sprint plans and task breakdowns using AI
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="sprint-goals">Sprint Goals</Label>
              <Textarea
                id="sprint-goals"
                placeholder="Describe what you want to achieve in this sprint..."
                className="mt-1"
              />
            </div>
            <div>
              <Label htmlFor="timeline">Timeline (days)</Label>
              <Input
                id="timeline"
                type="number"
                placeholder="14"
                className="mt-1"
              />
            </div>
            <div>
              <Label htmlFor="team-size">Team Size</Label>
              <Input
                id="team-size"
                type="number"
                placeholder="3"
                className="mt-1"
              />
            </div>
            <Button className="w-full">
              <Zap className="h-4 w-4 mr-2" />
              Generate Sprint Plan
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Blocker Tracker Dialog */}
      <Dialog open={showBlockerTracker} onOpenChange={setShowBlockerTracker}>
        <DialogContent className="max-w-4xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Flag className="h-5 w-5" />
              Blocker Tracker
            </DialogTitle>
            <DialogDescription>
              Track and manage project blockers and impediments
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            {mockBlockers.map((blocker) => (
              <BlockerCard key={blocker.id} blocker={blocker} />
            ))}
            <Button variant="outline" className="w-full">
              <Plus className="h-4 w-4 mr-2" />
              Add New Blocker
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Activity Timeline Dialog */}
      <Dialog open={showActivityTimeline} onOpenChange={setShowActivityTimeline}>
        <DialogContent className="max-w-4xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Activity className="h-5 w-5" />
              Activity Timeline
            </DialogTitle>
            <DialogDescription>
              Recent project activity and audit trail
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            {mockActivityLogs.map((log) => (
              <Card key={log.id} className="p-4">
                <div className="flex items-start gap-3">
                  <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center">
                    {log.actorType === 'agent' ? (
                      <Bot className="h-4 w-4 text-primary" />
                    ) : (
                      <User className="h-4 w-4 text-primary" />
                    )}
                  </div>
                  <div className="flex-1 space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-sm">
                        {log.actorType === 'agent' ? log.agentName : log.actorName}
                      </span>
                      <Badge variant="outline" size="sm">
                        {log.actorType}
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground">{log.description}</p>
                    <p className="text-xs text-muted-foreground">
                      {new Date(log.createdAt).toLocaleString()}
                    </p>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
